<?php
session_start();
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role'])) {
    header("Location: login.php");
    exit();
}

$user_id = $_SESSION['user_id'];
$user_role = $_SESSION['role'];

if ($user_role !== 'System Admin') {
    die("Access denied: You must be a System Admin to perform this action.");
}

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "ludeb";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Retrieve subjects
$subjects_query = "SELECT DISTINCT subject_id FROM results";
$subjects_result = $conn->query($subjects_query);

if (!$subjects_result) {
    die("Error retrieving subjects: " . $conn->error);
}

$subjects = [];
while ($subject_row = $subjects_result->fetch_assoc()) {
    $subjects[] = $subject_row['subject_id'];
}

// Prepare the output for each subject
$output = "";

foreach ($subjects as $subject_id) {
    // Retrieve candidates missing marks for the subject
    $query = "
        SELECT r.candidate_id, r.school_id, c.Candidate_Name AS candidate_name 
        FROM results r
        JOIN marks m ON r.candidate_id = m.candidate_id AND r.subject_id = m.subject_id
        JOIN candidates c ON r.candidate_id = c.id
        WHERE r.subject_id = ? AND r.aggregates > 9 AND r.division = 'X' AND m.mark IS NULL
        GROUP BY r.candidate_id, r.school_id
    ";

    $stmt = $conn->prepare($query);
    if (!$stmt) {
        die("Error preparing statement: " . $conn->error);
    }

    $stmt->bind_param("i", $subject_id);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows > 0) {
        $subject_name_query = "SELECT name FROM subjects WHERE id = ?";
        $subject_stmt = $conn->prepare($subject_name_query);
        if (!$subject_stmt) {
            die("Error preparing subject statement: " . $conn->error);
        }

        $subject_stmt->bind_param("i", $subject_id);
        $subject_stmt->execute();
        $subject_name_result = $subject_stmt->get_result();
        $subject_name_row = $subject_name_result->fetch_assoc();
        $subject_name = $subject_name_row['name'];

        $output .= "<h2>School Name - Candidates Missing Marks for $subject_name</h2>";
        $output .= "<table border='1'><tr><th>Index No</th><th>Candidate Name</th><th>Input for Marks</th></tr>";

        while ($row = $result->fetch_assoc()) {
            $output .= "<tr>
                            <td>{$row['candidate_id']}</td>
                            <td>{$row['candidate_name']}</td>
                            <td><input type='number' name='marks[{$row['candidate_id']}][{$subject_id}]' /></td>
                        </tr>";
        }

        $output .= "</table><br/>";
    }
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    foreach ($_POST['marks'] as $candidate_id => $subjects) {
        foreach ($subjects as $subject_id => $mark) {
            $mark = intval($mark);

            // Update the marks table
            $update_query = "
                UPDATE marks 
                SET mark = ?, updated_at = NOW(), edited_by = ? 
                WHERE candidate_id = ? AND subject_id = ? AND mark IS NULL
            ";

            $update_stmt = $conn->prepare($update_query);
            if (!$update_stmt) {
                die("Error preparing update statement: " . $conn->error);
            }

            $update_stmt->bind_param("iiii", $mark, $user_id, $candidate_id, $subject_id);
            $update_stmt->execute();
        }
    }

    // Optionally, update the results table here if needed

    echo "<p>Marks updated successfully.</p>";
}

$conn->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Missing Marks</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Update Missing Marks</h1>
        <form method="post">
            <?php
                // Output the content generated by PHP
                echo $output ? $output : "<p>No candidates missing marks found.</p>";
            ?>
            <button type="submit" class="btn btn-primary">Update Marks</button>
        </form>
    </div>
</body>
</html>
